// web/src/lib/strings.ts
export const strings = {
  explorer: "Explorer",
  productName: "Talaria",
  search: "Search",
  searchPlaceholder: "Search a historical figure…",
  searchHintCommit: "Pick the person — Talaria collects their life trace.",
  searchInLibrary: "In library",
  searchNew: "New",
  collectLifeTrace: "Collect life trace",
  collectLifeTraceHint:
    "Search starts Wikipedia, Wikisource, Commons and Wikidata. Run again to add more dated places to the map.",
  collectScholarship: "Collect scholarship",
  collectScholarshipHint:
    "HAL, Persée, theses, Gallica and catalogs → theories, controversies and academic works.",
  collecting: "Collecting sources…",
  ingestQueued: "Life-trace collection queued…",
  ingestRunning: "Collecting dated facts and places…",
  ingestRunningCounts: (timeline: number, map: number) =>
    `Collecting… ${timeline} dated facts, ${map} on the map`,
  ingestDone: "Life trace updated",
  agoraQueued: "Scholarship collection queued…",
  agoraRunning: "Collecting theses, debates and sources…",
  agoraDone: "Agora updated",
  ingestFailed: "Collection failed",
  laneExplorerTitle: "Life trace",
  laneExplorerHint: "Dated facts and anecdotes located in space and time.",
  laneAgoraTitle: "Agora",
  laneAgoraHint: "Theories, controversies, opinions and academic works about this person.",
  emptySearch: "Search a historical figure to open their geographic life trace.",
  emptyTimeline: "No dated facts yet. Collect the life trace to fill the map and timeline.",
  emptyAgora: "No scholarship yet. Collect sources to load theses, debates and bibliography.",
  loading: "Loading…",
  noResults: "No matches.",
  explorerMapTimelineBar: "Period",
  explorerPeriodFrom: "From year",
  explorerPeriodTo: "To year",
  explorerPeriodFilterTitle: "Period",
  explorerPeriodFilterEmpty: "Load events to filter by period.",
  explorerClearPeriod: "Reset period",
  explorerConfidenceFilterTitle: "Confidence",
  openProfile: "Open profile",
} as const;
