// web/src/lib/strings.ts
export const strings = {
  explorer: "Explorer",
  search: "Search",
  searchHintCommit: "Pick a suggestion or press Enter to search.",
  searchIngestBadge: "Ingest",
  ingestQueued: "Queued full density ingest…",
  ingestRunning: "Ingesting Wikipedia/Wikidata (density)…",
  ingestDone: "Density ingest complete — loading map…",
  ingestFailed: "Ingest failed",
  loading: "Loading…",
  noResults: "No matches.",
  explorerMapTimelineBar: "Period",
  explorerPeriodFrom: "From year",
  explorerPeriodTo: "To year",
  explorerPeriodFilterTitle: "Period",
  explorerPeriodFilterEmpty: "Load events to filter by period.",
  explorerClearPeriod: "Reset period",
  explorerConfidenceFilterTitle: "Confidence",
  openProfile: "Open profile",
} as const;
